apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: elastic-system
data:
  kibana.yml: |
    server.host: "0.0.0.0"
    server.name: "kibana"
    elasticsearch.hosts: ["http://elasticsearch:9200"]
    i18n.locale: "ko-KR"
    monitoring.ui.container.elasticsearch.enabled: true
